# -*- coding: utf-8 -*-
"""Untitled0 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aN_YhLyGV1qN2cGVX53DIb31lsPNvDLF
"""

from google.colab import files
uploaded = files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!pip install -q kaggle

!kaggle datasets download -d saroz014/plant-disease -p /content/raw --unzip

import os, shutil

dup_path = "/content/raw/dataset/dataset"
if os.path.exists(dup_path):
    shutil.rmtree(dup_path)
    print("Removed duplicate nested folder")

fixed = 0
for dirpath, dirnames, filenames in os.walk("/content/raw/dataset"):
    for fname in filenames:
        name, ext = os.path.splitext(fname)
        stripped = name.strip()
        if stripped != name:
            os.rename(os.path.join(dirpath, fname), os.path.join(dirpath, stripped + ext))
            fixed += 1
print(f"Fixed {fixed} filenames")

print(os.listdir("/content/raw/dataset"))
print(os.listdir("/content/raw/dataset/train"))

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import numpy as np

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

train_dir = "/content/raw/dataset/train"
test_dir = "/content/raw/dataset/test"

IMG_SIZE = 128
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator, val_generator = (
    train_datagen.flow_from_directory(train_dir, target_size=(IMG_SIZE, IMG_SIZE), batch_size=BATCH_SIZE, class_mode='categorical', subset=subset)
    for subset in ['training', 'validation']
)

test_generator = test_datagen.flow_from_directory(
    test_dir, target_size=(IMG_SIZE, IMG_SIZE), batch_size=BATCH_SIZE, class_mode='categorical', shuffle=False
)

num_classes = train_generator.num_classes
print("Number of classes:", num_classes)
print("Class indices:", train_generator.class_indices)

from tensorflow.keras.layers import Input

model = Sequential([
    Input(shape=(IMG_SIZE, IMG_SIZE, 3)),
    Conv2D(32, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(2,2),
])
model.add(Conv2D(128, (3,3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))

model.add(Conv2D(256, (3,3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])
callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ModelCheckpoint('best_model.keras', monitor='val_accuracy', save_best_only=True)
]

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=300,
    callbacks=callbacks
)

from google.colab import files
files.download('best_model.keras')

import json
with open('labels.json', 'w') as f:
    json.dump({v: k for k, v in train_generator.class_indices.items()}, f, indent=2)
files.download('labels.json')

model.save("best_model.h5")

from google.colab import files
files.download("best_model.h5")

import numpy as np
from sklearn.metrics import (
    precision_score, recall_score, f1_score,
    accuracy_score, confusion_matrix, classification_report
)

# ---------- Predict on the entire test set ----------
y_true = test_generator.classes          # true integer labels, in generator order
probs = model.predict(test_generator, verbose=1)
y_pred = np.argmax(probs, axis=1)        # convert predicted probabilities to class indices

# ---------- Overall metrics ----------
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average="weighted", zero_division=0)
recall = recall_score(y_true, y_pred, average="weighted", zero_division=0)
f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)

print(f"Accuracy:  {accuracy * 100:.2f}%")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1 Score:  {f1:.4f}")

# ---------- Per-class report ----------
idx_to_class = {v: k for k, v in test_generator.class_indices.items()}
target_names = [idx_to_class[i] for i in range(len(idx_to_class))]

print("\nPer-Class Report:")
print(classification_report(y_true, y_pred, target_names=target_names, zero_division=0))

# ---------- Confusion matrix ----------
cm = confusion_matrix(y_true, y_pred)

